[project]
name = "smpte-ltc-to-mtc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "audioop-lts>=0.2.1",
    "mido>=1.3.3",
    "pyaudio>=0.2.14",
    "python-rtmidi>=1.5.8",
]
